### ISSUE TITLE
TypeError: Type has kind any, expected interface (bundled with webpack)

### ISSUE THREAD

**Issue by navrocky** [typescript-rtti/typescript-rtti#107]
I try to use rtti with webpack and encounter such error, if reflected interface placed in other module.

```
import "reflect-metadata";
import { reflect } from "typescript-rtti";
import { IfaceFromModule } from "./module";

const iface = reflect<IfaceFromModule>().as("interface").reflectedInterface;
console.log(iface.propertyNames);
```

Error is: 
```
TypeError: Type has kind any, expected interface
    at E.as (/home/vlad/prog/tmp/typescript-rtti/dist/bundle.js:2:13252)
    at /home/vlad/prog/tmp/typescript-rtti/dist/bundle.js:2:44344
    at /home/vlad/prog/tmp/typescript-rtti/dist/bundle.js:2:44409
    at Object.<anonymous> (/home/vlad/prog/tmp/typescript-rtti/dist/bundle.js:2:44413)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

Here is a minimal project that reproduce this error: https://github.com/navrocky/webpack-typescript-rtti-bug

**Comment by rezonant** [comment]
Thanks for the minimal reproduction!

I'm having trouble getting your isolated test to exhibit the same behavior. I hit an issue with webpack/ts-loader trying to resolve `./module.js` and failing (since it would need to be `./module.ts` for ts-loader to pick it up), but a quick `extensionAlias: { '.js': ['.ts', '.js'] }` solved that, and then I get the following output on `npm start`:

![image](https://github.com/typescript-rtti/typescript-rtti/assets/409140/825ce419-7c08-43e4-bda3-3b1538ea9560)

Versions I ended up with after `npm i`:

```
typescript-rtti@1.0.0 D:\Dev\navrocky\webpack-typescript-rtti-bug
├── reflect-metadata@0.1.13
├── ts-loader@9.4.4
├── ts-patch@3.0.2
├── typescript-rtti@0.9.6
├── typescript@5.1.6
├── webpack-cli@5.1.4
└── webpack@5.88.2
```

The behavior you describe sounds like `transpileOnly` is getting set (or you are using an equivalent mode where each file is compiled independently from the rest). In those cases, the behavior you describe is expected.
