### ISSUE TITLE
Exporting an interface produces a js-require

### ISSUE THREAD

**Issue by alxgrk** [typescript-rtti/typescript-rtti#110]
Hi there,

I have the following interface defined in a module called `record.ts`, and it extends two other interfaces:
```ts
export interface C extends A, B {
  foo: string;
}
```

In another file, I'm trying to iterate all three interfaces A, B and C to get all their properties like so:
```ts
import type { C } from '../record';
import { reflect } from "typescript-rtti";

// ...

const reflectedInterface = reflect<C>().as('interface').reflectedInterface;
// iterate over properties and parent interfaces...
```

While this works correctly when running the dist/ files, it is not working with ts-node. This is because of the `import type { C } from '../record';` being translated to something like this:
```js
const __RΦ = { // ...
    }, t: { [670]: { LΦ: t => require("../record.js").IΦC }, // ...
```
Obviously, the `require("../record.js")` is the problem and can not be resolved by ts-node.
Is there any setting I'm missing? Why is this not written as `require("../record")` (without the `.js` suffix)?

Looking forward to an answer,
Alex

**Comment by rezonant** [comment]
Interesting, at the very least we should document this limitation. 

I'm not sure removing the suffix will fix the issue with ts-node.

**Comment by rezonant** [comment]
I'm testing this out a bit and I see this error, is this the one you see? If not, please post your error.

```
Error: Cannot determine relationship between an absolute and a relative path!
    at findRelativePathToFile (D:\Dev\typescript-rtti\typescript-rtti\dist\transformer\find-relative-path.js:14:15)
    at D:\Dev\typescript-rtti\typescript-rtti\dist\transformer\index.js:181:90
    at tspWrappedFactory (evalmachine.<anonymous>:223:31)
    at transformSourceFileOrBundle (evalmachine.<anonymous>:88433:51)
    at transformation (evalmachine.<anonymous>:110233:16)
    at transformRoot (evalmachine.<anonymous>:110256:73)
    at transformNodes (evalmachine.<anonymous>:110241:72)
    at emitJsFileOrBundle (evalmachine.<anonymous>:110828:26)
    at emitSourceFileOrBundle (evalmachine.<anonymous>:110763:7)
    at forEachEmittedFile (evalmachine.<anonymous>:110517:26)
```

**Comment by rezonant** [comment]
OK yeah there is a lot of "ifs" around this area. Will help if you can provide:
- Typescript version
- Typescript RTTI version
- tsconfig.json you are supplying to ts-node
- package.json `type` field
- The error output you get from ts-node

**Comment by alxgrk** [comment]
@rezonant , sorry for answering late, those are the requested infos:
 - Typescript version: 4.9.5
 - Typescript RTTI version: 0.9.6
 - tsconfig.json you are supplying to ts-node:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "declaration": true,

    "alwaysStrict": true,
    "forceConsistentCasingInFileNames": true,
    "removeComments": true,
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "composite": true,
    "skipLibCheck": true,
    "noEmitHelpers": false,
    "downlevelIteration": true,

    "outDir": "dist",
    "rootDir": "src",
    "baseUrl": ".",

    "plugins": [{"transform": "typescript-rtti/dist/transformer"}]
  },
  "ts-node": {
    "compiler": "ttypescript"
  },
  "exclude": ["dist", "node_modules"],
  "include": ["src"]
}
```
 - package.json type field: `"type": "commonjs"`
 - The error output you get from ts-node: 
```
    Error: Cannot find module '../record.js'
Require stack:
- .../src/module.ts
- .../src/main.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (.../node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.LΦ (.../src/module.ts:27:95)
    at Object.a (.../src/module.ts:15:23)
    at reflectSpaceOutput (.../src/module.ts:15:17)
    at findColumns (.../src/module.ts:43:38)
    at findCsvColumns (.../src/module.ts:94:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '.../src/module.ts',
    '.../src/main.ts'
  ]
}
```
