### ISSUE TITLE
DX issues with reflect-metadata / why is it only a peer dependency ?

### ISSUE THREAD

**Issue by bogeeee** [typescript-rtti/typescript-rtti#115]
... and not a normal dependency. That is the first thing, i'm wondering. 

The docs say:
> The type information is emitted using `reflect-metadata`. You'll need to import it as early in your application as
> possible and ensure that it is imported only once.

So there must be some reason behind it i assume. That's fine. But please in case of a peer dependency, there should be a better error message, when it was forgotten by the user. A forgotten
`import 'reflect-metadata'` in my testcase, gives me a 

```
TypeError: Reflect.hasMetadata is not a function

      at getFlags (node_modules/typescript-rtti/src/lib/reflect.ts:1828:18)
      at Function.for (node_modules/typescript-rtti/src/lib/reflect.ts:1906:21)
      at ReflectedClassRef.matchesValue (node_modules/typescript-rtti/src/lib/reflect.ts:449:34)
      at Object.<anonymous> (pythagora_tests/unit/matchesValueLib/matchesValue.test.ts:23:45)

```

And this is just a bad dev experience cause one has no clue and costed me some hours even as an experienced typescript-rtti user.

So you should, before every usage, make a check with a friendly error message like:
```
if(!Reflect) {
throw new Error("Package 'reflect-metadata' is not included. Please do an "import 'reflect-metadata'" as early as possible in your application");
}
```

Thanks for an improvement ;)

**Comment by bogeeee** [comment]
caution: Or you do have to check with:
`if(typeof Reflect === "undefined")`

Sound like the same, but there's just some difference when dealing with eventually present symbols - try it out.

Ah, i would try it and make a pull request, if you tell me, how the final bundling scripts work, to make the package.

**Comment by rezonant** [comment]
> ... and not a normal dependency. That is the first thing, i'm wondering.

The reason is because of how Node.js dependencies work. If all packages in your node_modules agree on which version of `reflect-metadata` should be used, then there's no issue, because NPM will hoist (aka "dedupe") `reflect-metadata` to the top of the module tree, and everything's good. 

Where it goes wrong is when different dependencies depend on different versions of `reflect-metadata`. 
In that case NPM will not dedupe them up to the top. If the dependencies themselves do `import "reflect-metadata"` then this happens:

1. outer `reflect-metadata` is initialized
2. bunch of code uses `Reflect.defineMetadata()` to store some metadata
3. inner `reflect-metadata` is initialized, replacing the original _and all associated metadata_
4. bunch more code uses `Reflect.defineMetadata()` to store more metadata
5. once app is fully booted, only half the metadata will be available: the half that was loaded _after_ the second `reflect-metadata` gets installed

I call this the "splitbrain" metadata problem. To avoid this situation, it has long been customary for libraries that depend on `reflect-metadata` to mark it as a peer dependency, because the only code that should be importing it is the entrypoint of the top level application.

> But please in case of a peer dependency, there should be a better error message, when it was forgotten by the user.

Yeah, that would be helpful.

I think adding a ton of ergonomics checks isn't a great idea because things might change in the near future- with ES decorators now readily available and the recent changes to `reflect-metadata` to make it able to be accessed without monkeypatching the (existing, and very standardized) `Reflect` builtin, plus the [decorator metadata proposal](https://github.com/tc39/proposal-decorator-metadata)...

That being said I'm entirely fine with a small number (or ideally one) well placed check. Probably the perfect place to put that is in `reflect()`. We would want to check for `'getMetadata' in Reflect` I think, and use that opportunity to explain to the user that `reflect-metadata` will need to be installed in order to use it.
