### ISSUE TITLE
TypeError when accessing class method parameters

### ISSUE THREAD

**Issue by StefanSafeguard** [typescript-rtti/typescript-rtti#24]
A TypeError occurs when I'm trying to access the parameters of a method when accessing a reflected class, this has to do with incorrect typings on `this.RtParameter` which can return undefined if there is no metadata defined with the key `rt:p`
> TypeError: Cannot read properties of undefined (reading 'map')
    at ReflectedMethod.get parameters [as parameters] (/Users/stefan/Git/Safeguard-API/docs/node_modules/typescript-rtti/src/lib/reflect.ts:1214:52)
    at ReflectedMethod.getParameter (/Users/stefan/Git/Safeguard-API/docs/node_modules/typescript-rtti/src/lib/reflect.ts:1223:21)

The issue here being that the parameter metadata is not being defined for this method, however even if the definition is missing the types are still incorrect as during runtime `undefined` is a possible type here.

**Comment by rezonant** [comment]
Actually that's in the `design:paramtypes` handling. Wouldn't have to do with `RtParameter` (which was incorrectly refactored, it should be called `rawParameterMetadata`.

Would you mind finding the output where `design:paramtypes`/`rt:p` is undefined and providing a snippet around that? Or better yet, if you are able to reproduce the bad output at https://typescript-rtti.org/, you can share the link back so we can use it to fix the issue. 

`design:paramtypes` should always emit as an array, or not be set if Typescript would not normally output it without our transformer active. This is the code that emits it for typescript-rtti:

```typescript
if (this.emitStandardMetadata && eligibleForLegacyDecorators && isDecorated)
    decs.push(metadataDecorator('design:paramtypes', standardParamTypes.map(t => literalNode(t))));
```

...for that to output `undefined`, either the metadata decoration emit code has a bug or perhaps `design:paramtypes` is being output from another source since it would have crashed at compile-time otherwise. I don't think Typescript outputs undefined in any cases.

Both `rt:p` and `design:paramtypes` should never be emitted as undefined, only as an array. If you are seeing `__RΦ.m("rt:p", undefined)` or anything other than `__RΦ.m("rt:p", [...])` in your output, that is a bug indeed. Again, snippets of the output and hopefully a small reproduction would be super helpful. Or if your code is public, just point me at it.

Since we should never crash here at runtime I have added a guard for handling bad emits and ensured that we always return an array from `parameters`. This is in `v0.4.12` and up. But this is just to prevent the crash at runtime- if you are getting undefined emitted into your output code, we should fix that.

> the types are still incorrect as during runtime undefined is a possible type here

Do you mean you seeing type errors in your own project originating from typescript-rtti? If so, do you have the TS' strict modes turned on? This codebase doesn't have any of the strict modes turned on, and I've been wondering if that's going to be a problem for projects which do. More than willing to solve that issue if so.

Thanks for trying this out, I'm sure we can get this issue fixed!

**Comment by StefanSafeguard** [comment]
Hmm, I'll try to see if I can make an example that reproduces the issue. Unfortunately the code I'm using it in is private. 

One thing that strikes me as odd in this, when I manually reflect one of the classes I have this issue on the typing result is not that of a reflected class but when running it it is of type `ReflectedClass`.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/70584680/156895743-a25754fc-58c7-4446-a1cb-8e7986fe7804.png">'

When running it is of type `ReflectedClass`:
```
ReflectedClass {
  _hasPropertyNamesMeta: false,
  _hasStaticPropertyNameMeta: false,
  _dynamicStaticProperties: Map(0) {},
  _dynamicProperties: Map(0) {},
  _class: [class LocationController extends BaseController]
}

The classes I'm working with are of `foo extends bar` where `bar` is abstract, both `foo` and `bar` have a class decorator, and all of the method parameters of `foo` have parameter decorators. 

So far I haven't been able to find the exact thing which makes it reproducible but I'll keep trying to see what it is.

**Comment by StefanSafeguard** [comment]
Hmm, it seems to be caused by external factors.

I've created a dummy class `foo` without any decorators or anything at all and on that class it fails as well. Do you happen to know if incorporating the `reflect-metadata` package can cause conflicts?

**Comment by rezonant** [comment]
First, just in case: make sure you are using the latest version of typescript-rtti, there have been a lot of bug fixes in the last few days.

> Do you happen to know if incorporating the reflect-metadata package can cause conflicts?

`reflect-metadata` is actually required for `typescript-rtti`. As always you should ensure that you have only one copy of `reflect-metadata` in your module tree or at least that only one `import "reflect-metadata"` call is happening, and it should be at the root of your application.

Oops, does look like `reflect-metadata` was not listed as a peer dependency. That is fixed in `v0.4.13`.

I tried to replicate the issue in the playground but it seems to be working: https://typescript-rtti.org/#aW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7CgpmdW5jdGlvbiBwYXJhbSgpIHsgCiAgICByZXR1cm4gKHRhcmdldCwgcHJvcGVydHlLZXksIGluZGV4KSA9PiB7CiAgICAgICAgUmVmbGVjdC5kZWZpbmVNZXRhZGF0YShgZm9vOnBhcmFtOiR7aW5kZXh9YCwgJ2JhcicsIHRhcmdldCwgcHJvcGVydHlLZXkpOwogICAgfQp9CgpmdW5jdGlvbiBtZXRob2QoKSB7CiAgICByZXR1cm4gUmVmbGVjdC5tZXRhZGF0YSgnZm9vJywgJ2JhcicpOwp9CgphYnN0cmFjdCBjbGFzcyBBIHt9CmNsYXNzIEIgZXh0ZW5kcyBBIHsKICAgIEBtZXRob2QoKSBmb28oCiAgICAgICAgQHBhcmFtKCkgYSA6IG51bWJlciwgCiAgICAgICAgQHBhcmFtKCkgYiA6IHN0cmluZywgCiAgICAgICAgQHBhcmFtKCkgYyA6IGJvb2xlYW4KICAgICkgeyByZXR1cm4gdHJ1ZSA/IDEyMyA6ICdmb28nOyB9CiAgICBiYXIoKSB7IHJldHVybiBmYWxzZTsgfQp9CgovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgpjb25zb2xlLmxvZygnVGhlIHR5cGUgb2YgcmVmbGVjdChCKSBpczonLCByZWZsZWN0KEIpLmNvbnN0cnVjdG9yLm5hbWUpOwpjb25zb2xlLmxvZygnVGhlIG1ldGhvZCBuYW1lcyBhcmU6JywgcmVmbGVjdChCKS5tZXRob2ROYW1lcyk7CmNvbnNvbGUubG9nKAogICAgJ1RoZSBwYXJhbWV0ZXIgbmFtZXMgZm9yIGZvbygpOicsIAogICAgcmVmbGVjdChCKS5nZXRNZXRob2QoJ2ZvbycpLnBhcmFtZXRlck5hbWVzCik7Cg==

However, perhaps this has to do with different compilation units. For instance, if there was a B function declaration, which is only valid when the B class is ambient, that might cause the issue. Maybe something like this?

https://typescript-rtti.org/#aW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7CgphYnN0cmFjdCBjbGFzcyBBIHsKICAgIGNvbnN0cnVjdG9yKHJlYWRvbmx5IGEgOiBudW1iZXIpIHsgfTsKfQpkZWNsYXJlIGNsYXNzIEIgZXh0ZW5kcyBBIHsKICAgIGNvbnN0cnVjdG9yKCk7CiAgICAKICAgIGZvbyhhIDogbnVtYmVyLCBiIDogc3RyaW5nLCBjIDogYm9vbGVhbik7CiAgICBiYXIoKTsKfQoKZnVuY3Rpb24gQiAoKSB7IH0KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCmNvbnNvbGUubG9nKCdUaGUgdHlwZSBvZiByZWZsZWN0KEIpIGlzOicsIHJlZmxlY3QoQikuY29uc3RydWN0b3IubmFtZSk7CmNvbnNvbGUubG9nKCdUaGUgbWV0aG9kIG5hbWVzIGFyZTonLCByZWZsZWN0KEIpLm1ldGhvZE5hbWVzKTsKY29uc29sZS5sb2coCiAgICAnVGhlIHBhcmFtZXRlciBuYW1lcyBmb3IgZm9vKCk6JywgCiAgICByZWZsZWN0KEIpLmdldE1ldGhvZCgnZm9vJykucGFyYW1ldGVyTmFtZXMKKTsK

![image](https://user-images.githubusercontent.com/409140/156901839-dec5c8d9-f5fb-48d9-b736-3462784de658.png)

**Comment by rezonant** [comment]
I'm currently working through issues with the TypeORM codebase that could have positive impacts for your codebase, I'll post here once that's green, perhaps your codebase is running into similar issues

**Comment by rezonant** [comment]
Maybe you could give `v0.4.16` a try to see if anything is improved? It has some improvements found while enabling `typeorm` builds in the test suite.

**Comment by StefanSafeguard** [comment]
I'll try it out with the update, I think that I might have an idea as to what is causing my issue. I'm currently using this package in a separate TS project directory which consumes the code of a separate application that resides in a different project directory, I think my issue is that the dependant project is not being build using the same typescript-rtti transformer which would explain the missing `rt:p` and explains why `design:paramtypes` is filled, because that project is using `reflect-metadata`

**Comment by rezonant** [comment]
I was wondering about this, but it is worth noting that `reflect()` is expected to work with code that has emitDecoratorMetadata emitted for it, at least to the limited level it can. For the full breadth of facts it can introspect though the source definition should be compiled with typescript-rtti.

So for instance, if you have a method decorated with design:returntype, then reflect(Class).getMethod('foo').returnType should give you a ReflectedClassRef for the class constructor that the design:returntype metadata key contains.

The longer term goal is for `reflect()` to be independent of this project, so that it can support any and all useful runtime metadata formats and schemes.

**Comment by rezonant** [comment]
The next release is going to overhaul the handling of cross-module/package imports (#27, #28), which may also be relevant to your use case. There is an additional issue regarding `npm link` and symbolic links in general at #29 which is still outsanding.

**Comment by StefanSafeguard** [comment]
I see that you've just released with those fixes, I'll try and squeeze some time in today to update and play around with :)

**Comment by StefanSafeguard** [comment]
Lol, I was stupid. I messed up the argument order to `ts-node`.... :')

**Comment by StefanSafeguard** [comment]
Seems like the metadata builder does not handle `string[]` vs `Array<string>` correctly, it errors out when using `string[]` 😄

**Comment by rezonant** [comment]
Can confirm, the following test fails:

```typescript
    it.only('emits for array types with noLib', async () => {
        let exports = await runSimple({
            code: `
                interface I {
                    foo : number;
                }

                export class C {
                    method(): string[] { return null; }
                }
            `,
            compilerOptions: {
                noLib: true
            }
        });

        let type = Reflect.getMetadata('rt:t', exports.C.prototype, 'method');
        expect(type()).to.eql({ TΦ: T_ARRAY, e: String });
    })
```

**Comment by StefanSafeguard** [comment]
Hmm, I'll check. I know for sure that I have not added a `noLib` setting manually

**Comment by rezonant** [comment]
Ooh ok I know where that is. This works much better with the RTTI format, we just need to backport those improvements to emitDecoratorMetadata

**Comment by StefanSafeguard** [comment]
Ah cool! For know I've rewritten al my default exports in order for them to work. The project in itself is still in transition from being rewritten into TS from JS so there's still a lot of stuff you run into when trying to use certain TS settings/features.

**Comment by rezonant** [comment]
OK, version 0.5.2 is out with fixes for design:* metadata, give it a shot and give a shout if you find any issues!
