### ISSUE TITLE
Cannot find module '........../node_modules/typescript-rtti/dist/lib/reflect'

### ISSUE THREAD

**Issue by capaj** [typescript-rtti/typescript-rtti#28]
On some version between 0.2.0 and 0.4.16 I started getting this error when I run jest specs in decapi.

```
 FAIL  src/domains/field/Field.spec.ts
  ● Test suite failed to run

    Cannot find module '........../node_modules/typescript-rtti/dist/lib/reflect' from 'src/services/utils/gql/types/inferTypeByTarget.ts'

      14 | // tslint:disable-next-line: use-primitive-type
      15 | export type ParsableScalar = String | Number | Boolean | Date
    > 16 |
         | ^
      17 | export function isParsableScalar(input: any): input is ParsableScalar {
      18 |   return [String, Number, Boolean, Date].includes(input)
      19 | }

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.LΦ (src/services/utils/gql/types/inferTypeByTarget.ts:16:102)
      at Object.a (src/services/utils/gql/types/inferTypeByTarget.ts:11:23)
      at RΦ (src/services/utils/gql/types/inferTypeByTarget.ts:16:52)
      at Object.a (src/services/utils/gql/types/inferTypeByTarget.ts:8:23)
```

I will try to pinpoint the exact version where this starts.

**Comment by capaj** [comment]
By further tests, it seems this wan introduced somewhere between 0.4.4 and 0.4.11

**Comment by rezonant** [comment]
Yep, this is related to #27 -- import logic needs an overhaul

**Comment by rezonant** [comment]
OK, version 0.4.17 is now out which should fix this issue. I ran the `rtti-wip` branch of decapi with it and the build fails, but for Typescript-related reasons (I don't think they are RTTI's fault).

**Comment by capaj** [comment]
this particular problem is confirmed fixed on my end
