### ISSUE TITLE
0.6 breaks tests for enums in decapi

### ISSUE THREAD

**Issue by capaj** [typescript-rtti/typescript-rtti#57]
This test: https://github.com/capaj/decapi/blob/rtti-wip/src/domains/enum/enum.spec.ts#L8

runs fine in jest when using 0.5.6, but breaks with this:
```
 FAIL  src/domains/enum/enum.spec.ts
  ● Enums › renders schema with an enum used in a query

    ReferenceError: StateEnum is not defined

      24 |       )
      25 |     }
    > 26 |     try {
         |                    ^
      27 |       registerEnum(Foo2, 'Foo2')
      28 |     } catch (err) {
      29 |       expect(err).toMatchInlineSnapshot(

      at RΦ (src/domains/enum/enum.spec.ts:26:136)
      at Object.a (src/domains/enum/enum.spec.ts:18:23)
      at Object.t (src/domains/enum/enum.spec.ts:185:53)
      at node_modules/typescript-rtti/src/lib/reflect.ts:1452:73
          at Array.map (<anonymous>)
      at ReflectedMethod.get parameterTypes [as parameterTypes] (node_modules/typescript-rtti/src/lib/reflect.ts:1451:69)
      at compileFieldArgs (src/domains/arg/compiler.ts:112:27)
      at compileFieldConfig (src/domains/field/compiler/fieldCompiler.ts:31:32)
      at src/domains/schema/rootFields.ts:38:30
      at Object.keys.forEach.__RΦ.f.__RΦ.m.n (src/domains/schema/compiler.ts:26:27)
```

When I update to 0.6.0.
The error goes away when I move the definition of these enums:
```ts
    enum IntEnum {
      one,
      two
    }

    enum StateEnum {
      Done = 'DONE',
      In_Progress = 'IN_PROGRESS',
      Finished = 'FINISHED',
      Cancelled = 'CANCELLED'
    }

    enum StateEnumUsingKeys {
      Done = 'DONE',
      InProgress = 'INPROGRESS',
      Finished = 'FINISHED',
      Cancelled = 'CANCELLED'
    }
```

to the top level.

**Comment by rezonant** [comment]
OK, not unexpected that there would be some resolution issues with the new enum reflection. Similar to classes and interfaces, enum objects must be imported as part of their type reference. I should add the new decapi betas to corpus to catch  these issues as well, right now we're just doing the original version that doesn't use RTTI.

**Comment by rezonant** [comment]
OK the core issue here is fixed, but there's still a failure in `rtti-wip`:

```
Summary of all failing tests
FAIL src/domains/enum/enum.spec.ts
  ● Enums › renders schema with an enum used in a query

    @ObjectType FooSchema.echoAsInferred: Could not infer return type and no type is explicitly configured. In case of circular dependencies make sure to explicitly set a type.

      37 |   let gqlType
      38 |   if (type) {
    > 39 |     // console.log(fieldName, '~ isNullable', isNullable)
         |                   ^
      40 |
      41 |     gqlType = resolveTypeOrThrow(
      42 |       { runtimeType: type, isNullable: isNullable ?? inferredType.isNullable },

      at compileFieldConfig (src/domains/field/compiler/fieldCompiler.ts:39:19)
      at src/domains/schema/rootFields.ts:43:16
      at fieldConfigGetter (src/domains/schema/compiler.ts:51:33)
          at Array.forEach (<anonymous>)
      at forEach (src/domains/schema/compiler.ts:49:33)
      at getAllRootFieldsFromRegistry (src/domains/schema/compiler.ts:76:19)
      at Object.<anonymous> (src/domains/enum/enum.spec.ts:141:33)


Test Suites: 1 failed, 27 passed, 28 total
Tests:       1 failed, 4 skipped, 1 todo, 122 passed, 128 total
Snapshots:   61 passed, 61 total
Time:        10.179 s
Ran all test suites.
```

**Comment by rezonant** [comment]
Going to release a new RTTI for now to get all these fixes out-- unsure if the above is on RTTI or perhaps because you've been skipping the enum tests during dev. Will dig in more later

**Comment by capaj** [comment]
Actually the minimal spec I can repro this with is:

```ts
import { registerEnum } from '../..'
import { SchemaRoot, compileSchema } from '../schema/SchemaRoot.js'
import { Query } from '../schema/rootFields.js'
import { Arg } from '../arg/ArgDecorators.js'

enum IntEnum {
  one,
  two
}

describe('Enums', () => {
  it('renders schema with an enum used in a query', async () => {
    registerEnum(IntEnum, { name: 'IntEnum' })
    @SchemaRoot()
    class FooSchema {
      @Query()
      enumNullable(@Arg() input: IntEnum): IntEnum | null {
        return input
      }
    }
    const schema = compileSchema(FooSchema)
  })
})
```
