### ISSUE TITLE
Uncaught TypeError: Type has kind literal, expected interface

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#58]
Hello! 
When I try to perform reflect on an interface that is loaded from another package, I get an error! What to do?

```typescript
import {IMovable} from 'khusamov-game-command-system';

const theSpaceship = resolve<IMovable>('Adapter', game.theSpaceship, reflect<IMovable>())
```

Error:

```
reflect.js:173 Uncaught TypeError: Type has kind literal, expected interface
    at ReflectedLiteralRef.as (reflect.js:173:19)
    at adapterSourceGenerator (index.es.js:2198:49)
    at index.es.js:2250:20
    at IoC.resolve (index.es.js:2077:16)
    at Function.resolve (index.es.js:2067:42)
    at resolve (index.es.js:2295:16)
    at Application.tsx:13:22
    at index.js:6:77
    at index.js:7:3
```

**Comment by rezonant** [comment]
First, is the other package also compiled with the transformer?

If not, this is still a bug as you should get type reference kind "any" not literal.

Could you post the content of the compiled .js for this file?

**Comment by khusamov** [comment]
> First, is the other package also compiled with the transformer?

Yes, both packages are compiled with transformer. I checked it on purpose.

**Comment by khusamov** [comment]
> Could you post the content of the compiled .js for this file?

I will try to localize the error in a separate repository.

I will send a link to the repository and the compiled file.

**Comment by rezonant** [comment]
Any luck reproducing in an isolated repository?
