### ISSUE TITLE
Rollup+SVGR+RTTI: Failed to build source file Unexpected token R in JSON at position 0 

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#64]
Did you have any problems when sharing with the SVGR plugin for Rollup.js

https://react-svgr.com/docs/rollup/

Error text:

```
➤ RTTI: Failed to build source file /Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/packages/khusamov-game/src/components/Canvas/index.ts: Unexpected token R in JSON at position 0 [please report]
➤ SyntaxError: Unexpected token R in JSON at position 0
➤     at JSON.parse (<anonymous>)
➤     at MetadataEmitter.export (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript-rtti/src/transformer/metadata-emitter.ts:147:56)
➤     at /Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript-rtti/src/transformer/common/visitor-base.ts:66:44
➤     at visitNodes (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript/lib/typescript.js:87753:48)
➤     at visitLexicalEnvironment (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript/lib/typescript.js:87793:22)
➤     at Object.visitEachChild (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript/lib/typescript.js:88341:55)
➤     at /Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript-rtti/src/transformer/common/visitor-base.ts:59:27
➤     at Object.visitNode (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript/lib/typescript.js:87700:23)
➤     at MetadataEmitter.visitNode (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript-rtti/src/transformer/common/visitor-base.ts:84:19)
➤     at Function.emit (/Users/khusamov/Documents/repo/github.com/khusamov/solid-futurio-ru-game/node_modules/typescript-rtti/src/transformer/metadata-emitter.ts:15:41)

```

**Comment by rezonant** [comment]
This would have been us trying to parse a module name (which should be a double-quoted string). Should be fixable if you can provide a reproduction repo.

**Comment by rezonant** [comment]
I suspect this may be resolved, but if it's not please reopen. I have an idea of how we might make it work. But I'll need a reproduction repro to work on it.
