### ISSUE TITLE
compiler try to import a declaration file ('mongoose/types'): error module not found

### ISSUE THREAD

**Issue by CristianPi** [typescript-rtti/typescript-rtti#66]
v0.6.1

Configured project:
https://github.com/CristianPi/fullstack-monorepo-boilerplate/tree/rtti (branch rtti)
to start
```bash
npm i && npm run dev
```
### error

```bash
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'mongoose/types'
Require stack:
- /home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.mongoose/types (/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js:708:18)
    at __webpack_require__ (/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js:760:41)
    at Object.LΦ (/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js:581:532)
    at Object.a (/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js:576:23)
    at RΦ (/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js:581:444)
    at Object.a (/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js:573:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/cristian/IdeaProjects/fullstack-monorepo-boilerplate/dist/apps/api/main.js'
  ]
}

```
it seems that is trying to import a declaration file, not sure how to solve this?

**Comment by rezonant** [comment]
My day job has been particularly taxing in the last few weeks, and this clearly requires a framework-specific deep dive. If anyone following the project is willing to jump in and ascertain problems related to Mongoose, that would be great :-D

**Comment by CristianPi** [comment]
cannot reproduce anymore
